from __future__ import annotations

import html
from typing import Any

import httpx

from ..errors import ConfigurationError, WitnessError

DEFAULT_GITHUB_API_URL = "https://api.github.com"
MAX_COMMENT_CHARS = 65_000


def _text(value: Any, fallback: str = "Not provided.") -> str:
    rendered = str(value or "").strip()
    return rendered if rendered else fallback


def _evidence_link(finding: dict[str, Any]) -> str:
    evidence = _text(finding.get("evidence_path"), "")
    if not evidence:
        return "No evidence artifact was recorded."
    # Markdown destinations can be broken by whitespace or parentheses. Angle brackets keep
    # local artifact paths and absolute URLs readable without treating them as raw HTML.
    return f"[Open evidence](<{evidence}>)"


def format_findings_as_pr_comment(result: dict[str, Any]) -> str:
    """Render a bounded, evidence-first PR comment from Witness result JSON."""

    findings = result.get("findings") or []
    if not isinstance(findings, list):
        raise ValueError("result.findings must be a list")
    status = _text(result.get("overall_status"), "unknown")
    profile = result.get("profile") if isinstance(result.get("profile"), dict) else {}
    metadata = result.get("metadata") if isinstance(result.get("metadata"), dict) else {}
    usage = metadata.get("usage") if isinstance(metadata.get("usage"), dict) else {}
    target = _text(profile.get("target"), "unknown target")
    lines = [
        "<!-- witness-qa-comment -->",
        "## Witness QA",
        "",
        f"**Status:** `{status}`  ",
        f"**Target:** `{target}`  ",
        f"**Findings:** {len(findings)}  ",
    ]
    if usage:
        lines.append(
            f"**Estimated provider cost:** `${float(usage.get('estimated_cost_usd', 0.0) or 0.0):.6f}`"
        )
    if result.get("budget_exceeded"):
        lines.extend(
            [
                "",
                "> [!WARNING]",
                "> The configured provider-cost budget was exceeded. Witness preserved the evidence and stopped before the next action.",
            ]
        )
    lines.extend(["", "### Evidence-backed findings", ""])
    if not findings:
        lines.extend(
            [
                "No product mismatch was recorded in this run.",
                "",
            ]
        )
    for index, raw in enumerate(findings, start=1):
        if not isinstance(raw, dict):
            continue
        severity = _text(raw.get("severity"), "info").upper()
        summary = _text(raw.get("summary"), "Unnamed finding")
        fingerprint = _text(raw.get("fingerprint"), "unknown")
        lines.extend(
            [
                f"<details><summary><strong>{index}. [{html.escape(severity)}] {html.escape(summary)}</strong></summary>",
                "",
                f"- **Expectation:** {_text(raw.get('expectation'))}",
                f"- **Observed:** {_text(raw.get('observation'))}",
                f"- **Judgment:** {_text(raw.get('reasoning'))}",
                f"- **Suggested investigation:** {_text(raw.get('suggested_investigation'))}",
                f"- **Evidence:** {_evidence_link(raw)}",
                f"- **Fingerprint:** `{fingerprint}`",
                "",
                "</details>",
                "",
            ]
        )
    report_path = result.get("report_path")
    if report_path:
        lines.extend([f"Full report: [open Witness report](<{report_path}>)", ""])
    lines.extend(
        [
            "_Generated by Witness. Review evidence before merging or applying automated fixes._",
        ]
    )
    body = "\n".join(lines)
    if len(body) > MAX_COMMENT_CHARS:
        body = (
            body[: MAX_COMMENT_CHARS - 250]
            + "\n\n> Comment truncated to GitHub's safe size. Open the full Witness report for remaining findings.\n"
        )
    return body


def post_pr_comment(
    *,
    result: dict[str, Any],
    token: str,
    repository: str,
    pr_number: int,
    api_url: str = DEFAULT_GITHUB_API_URL,
    timeout: float = 30.0,
) -> dict[str, Any]:
    """Post a Witness result as a GitHub pull-request issue comment."""

    if not token.strip():
        raise ConfigurationError("GITHUB_TOKEN is required to post a PR comment")
    if repository.count("/") != 1 or any(not part for part in repository.split("/")):
        raise ConfigurationError("repository must be in owner/name form")
    if pr_number < 1:
        raise ConfigurationError("PR_NUMBER must be a positive integer")
    body = format_findings_as_pr_comment(result)
    endpoint = f"{api_url.rstrip('/')}/repos/{repository}/issues/{pr_number}/comments"
    try:
        with httpx.Client(timeout=timeout, follow_redirects=True) as client:
            response = client.post(
                endpoint,
                headers={
                    "Authorization": f"Bearer {token}",
                    "Accept": "application/vnd.github+json",
                    "X-GitHub-Api-Version": "2022-11-28",
                    "User-Agent": "witness-qa",
                },
                json={"body": body},
            )
    except httpx.HTTPError as exc:
        raise WitnessError(f"GitHub comment request failed: {exc}") from exc
    if response.status_code not in {200, 201}:
        detail = response.text[:2_000]
        raise WitnessError(f"GitHub comment request returned {response.status_code}: {detail}")
    payload = response.json()
    if not isinstance(payload, dict):
        raise WitnessError("GitHub comment response was not a JSON object")
    return payload
